name: Update README Year

on:
  schedule:
    - cron: '0 0 1 1 *' # Every January 1st
  workflow_dispatch:    # Allow manual trigger too

jobs:
  update-year:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update Year in README
        run: |
          current_year=$(date +%Y)
          sed -i "s/© [0-9]\{4\}/© $current_year/" README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update copyright year to $current_year"
          git push
